CREATE USER arithmetix_admin WITH PASSWORD 'admin';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO arithmetix_admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO arithmetix_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO arithmetix_admin;
