CREATE USER arithmetixAdmin WITH PASSWORD 'admin';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO arithmetixAdmin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO arithmetixAdmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO arithmetixAdmin;